# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

env:
  variables:
    PROJECT_NAME: multi-env-stack-with-cicd

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 18.x
  build:
    on-failure: ABORT
    commands:
      - PROJECT_ROOT_DIR="$(pwd)/$PROJECT_NAME"
      - cd $PROJECT_ROOT_DIR/infra
      - npm install
      - npm run test
      - npm run cdk synth
      - cd $PROJECT_ROOT_DIR/lambda-app/infra
      - COMMIT_ID=$(git rev-parse HEAD)
      - npm install
      - npm run test
      - npm run cdk synth
artifacts:
  files:
    - '**/*'
  name: commit-$COMMIT_ID
  base-directory: multi-env-stack-with-cicd/infra/cdk.out
